version: '3.8'

services:
  backend:
    build: ./book-api
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - ./book-api/.env
    volumes:
      - ./book-api:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 5s

  frontend:
    build: ./book-client
    container_name: angular_app
    ports:
      - "4200:4200"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./book-client:/app
      - /app/node_modules
    command: npm run start -- --host 0.0.0.0
